### ISSUE TITLE
GTD

### ISSUE THREAD

**Issue by PoBlue** [PoBlue/Note#1]
写写最近对 GTD （Get Things Done）的运用和一些看法

我觉得 GTD 的核心其实有点跟 2/8 法则差不多，就是要做 20% 的事成 80% 的功。

最近做事，要考虑以下的几点：

# 0 动力
参考二楼 Will 的观点：让 [本我](https://zh.wikipedia.org/zh-cn/本我、自我与超我) 认何一件事情，用本能的欲望，提供自己满满的能源

另外我补充一些小技巧：

### 为什么 vs 是什么
- 为什么：如果想要有干劲儿，增强自制力，则做这件事前，不断问自己为什么要做，想想行为背后更大的意义和目的
- 是什么:  如果遇到的是一件棘手的，有难度的事，则要问自己是什么，即事的具体步骤，专注于具体的必要行动，防拖延

### 进取 vs 防御
- 进取：想更快地逼近目标。积极，乐观地想象结果，如聚焦于锻炼（戒烟，学习）能带给你的收获
- 防御：想要更加谨慎，小心。悲观，消极地想象结果可能不如人意愿，尽量放大悲观性，如：买车票，想象自己会买错日期，或者之类的，那么我们就可以更加的小心

保守的策略：用 *进取* 快速逼近目标，一旦达到目标，再用 *防御* 进行适当的维护，免得前功尽弃

### 

# 1 优先级
所做的事对自己的目标是否有帮助，越有帮助优先级别就越高。其实很多的成功学都要别人想清楚目标，也不是无道理的。因为目标明确后，可以对事情划分 4 个象限：
1. 重要紧急
2. 重要不紧急
3. 不重要紧急
4. 不重要不紧急

每天对事情想清楚这几点，就可以尽量一步一步往自己目标靠近了。

# 2 DRY
Don't Repeat Yourself, 事情尽量自动化，一次做好！

一旦收到邮件还是什么都事情，5 分钟内能解决，就解决掉，当然这个 5 分钟看你怎么定义琐事。尽量避免一件事重复做，譬如：看了一眼短信或者邮件之类的，想了很多计划，但是推迟以后再做，相对比较浪费时间⌚️ 因为以后的话再做这件事又必须花时间重回这个 Context (上下文)。所以紧急的琐事尽快干掉。

另外对与零碎的通知，如短信，邮件，微信这些信息通知，尽量统一一个时间处理。
最好尽量电话。因为短信，微信这些无论打字还是语音，都需要大量的时间等待别人一来一回的回复。

# 3 委托
因为人不是万能的，遇到有些事情不是自己能力范围内的，或者对自己目标没有帮助的，或者是别人做的效率更高的时候，就委托让别人做。当然别人不可能无条件做的。要考虑付出来尽量委托，合作

# 4 习惯
还有一件很重要的东西，习惯，让一些很重复的琐事交给潜意识，让它自然而然地完成。

养成习惯可以参考书：[微习惯](https://book.douban.com/subject/26877306/)。里面讲到养成习惯可以设置每天最低目标，一定要低，低到你觉得不用 5 分钟就能完成，如锻炼，就每天只做一个俯卧撑。这样就能让自己习惯每天运动。每天可以超量，但是不能不做。自然习惯就能完成。

还有本 [习惯的力量](https://book.douban.com/subject/20507212/)，如果想养成一些有困难的习惯，一定要在完成困难的事情后及时奖励自己，如：今天做了 100 个俯卧撑，超量了，那么就奖励自己买一个 50 块的东西。久而久之，这种奖励模式，会让自己爱上克服困难，因为你知道困难背后有一道美丽的彩虹🌈

**Comment by weierz** [comment]
提供另一个视角：
## 0 Motivation

[本我](https://zh.wikipedia.org/zh-cn/本我、自我与超我)是提供动力的源泉，在开始前想清楚自己为什么要做这一件事，最好让本我认可这一件事。在充满激情的情况下，就可以飞速前进了。


另外，第一个的标题用 **优先级** 可好？
