### ISSUE TITLE
2018 前半年

### ISSUE THREAD

**Issue by PoBlue** [PoBlue/Note#10]
今年快要过一半了，今年的目标却仍未达成一半。

简单总结前半年：不坚持行动就废了，还养成了很多坏习惯

最差的口头禅/思想排行：
1. 明天开始好好干/待会再干，结果就没然后了
2. 做好了 A ，再做 B，结果 A 永远不会开始
3. 不再相信美好的明天会到来，不想拥抱变化。自身思想框架不够流通。

**Comment by WillBeethoven** [comment]
我也有相同的处境，所以我在想自己制定的东西为什么不开始做：

1. **内在**：提供源动力的本我是享乐主义，而一帆风顺又学不到什么东西，所以要先驾驭这头大象。
2. **目的**：我为什么要做这个？它和我活在这个世界上有什么关系？（驾驭大象）
3. **细分**：我做的这个事具体有什么最底层的小目标组成？（大象鼻子前的草）
4. **方法**：`一旦你足够了解某种特性，就一定会有它的用武之地 -- 《Java 编程思想》`
5. **行动**：让理智去审查身体的行动，确保方向正确。专注并享受这做件事的过程，而不是把这件事完成这个结果。这是我为什么没有再使用任务列表，因为它看起来是像工作一样需要完成的事，而且想完成的越多，任务就越重，压力就越大，但这些本应该是自己内在自发想要做的事，到最后自己却不想做了。
