### ISSUE TITLE
【年回顾】2017

### ISSUE THREAD

**Issue by PoBlue** [PoBlue/Note#9]
## 1 月
- 坚持了一个月的锻炼，每天锻炼 30 分钟，达成了 Apple Watch 坚持一个月锻炼的成就。只坚持 2 个月，忘了怎么就不坚持了。。
- 月尾报名了 Deep Learning ND，新年的时候赶过进度，后来就在临课程（总6个月）结束的最后两个月加速学习完了
- 买了 3ds 和 bose qc 35 降噪耳机，开始了剁手。。

## 2 月
- 去武汉旅游顺便过年
- 报名英语流利说，在群里认识了 2 位同学，然后组队，坚持每天半小时练习了4 个月。最后两个月队里的人散了，自己也就未能坚持下去了。结果是，听力和对话加强了很多

## 3 月

- 看了 BBC 纪录片 [美国商业大亨传奇](https://www.bilibili.com/video/av3313607/)，讲了很多商业伟人的故事，太震撼了
-  看了点[10分钟速成课：经济学](https://www.bilibili.com/video/av5525125/)，只看了一半，后来弃掉了

## 4 月
 - 加入了 Udacity ipnd 的字幕组，进行翻译，练习了一波听力和 Github 的一些用法, 持续了两个多月

## 5 月
- 开启了利用正则表达式进行 Review 的项目：[auto-review](https://github.com/PoBlue/auto-review), 在 5 月底完成了基本功能，然后就一直放置到年尾才拿出来加了些功能和完善

## 6 月
- 又重新开始锻炼和练习英语坚持一个月
- 成为 前端 1 对 1 导师
- 成为 Android 1 对 1 导师
- 顺便赶 Deep Learning 月尾的时候赶完，然后报名 AIND

## 7 月
- 开始养成了基本每个星期去温泉的习惯，坚持到现在
- 成为 ipnd 的优等生助教，持续了 2 个月

## 8 月
- 去越南旅游

## 9 月
- 剁手了 MacBook Pro 15 
- 开始养成每晚阅读的习惯，坚持到现在
- 成为 abnd 的优等生助教，直到现在

## 10 月
- 养成了每天写日记习惯，坚持到现在
- 完成商业分析基础学位
- 学习完了 React ND 
- 成为 React Reviewer

## 11 月
- 双十一剁手了 HHKB 
- 每晚玩一点游戏，通关了 《大逆转裁判 2》
- 坚持每天提交一点代码或者 issue 在 GitHub 上，坚持了一个月，后面就断断续续了
- 开始爬取 Udacity 的 Review ：[review-crawler](https://github.com/PoBlue/review-crawler)
- 和同学练习 BEC 英语，并且考了试，和她约定好今年 2018 年要考研
- 看了周杰伦演唱会，算是圆了一个梦了

## 12 月
- 买了 NS ，每晚因为游戏基本都很晚睡，影响睡眠啊，幸好现在已经打爆了想玩的游戏
- 看< Head First 设计模式> , 为每个模式整理做出 UML 图：[Head First Design Pattern](https://github.com/PoBlue/small_script/tree/master/head-first-design-pattern)，还未看完
- 看 <与爱因斯坦月球漫步：美国记忆力冠军教你记忆一切> ，看了 80% ，决定 2018 要重新收拾起高中的时候学习过的：记忆宫殿
- 打爆了 《塞尔达：荒野之息》
- 每晚听 20 分钟左右的 《苏菲的世界》 英文广播

 ## 总结
中间的有太多个月太废了，很多时间都没有很好利用就消逝了。自己也进步得不多。我觉得造成这样的主要原因是：
1. 没有明确的目标
2. 没有良好的反馈。应该像玩游戏那样把进度量化，那样会更加清楚自己的方法是否要改进和如何寻求突破

**Comment by weierz** [comment]
可以考虑读[佐治亚的在线硕士](http://www.omscs.gatech.edu)，Walker 就是。
